name           = "App-Greple-L"
badges         = [ "github-actions/test", "metacpan" ]
module_maker   = "ModuleBuildTiny"
static_install = "auto"
authority      = "cpan:UTASHIRO"

[release]
branch = "main"

[unsupported]
os = [
    "MSWin32",
]
